
import json
import os
import sys
from datetime import datetime
import contextlib
from cortex.config import EXAMPLES_DIR
from cortex.graph import run_incident
from cortex.models import Incident

# --- Configuration ---
TARGET_URN = "urn:li:dataset:(urn:li:dataPlatform:snowflake,b2fd91.order_entry_db.analytics.order_details,PROD)"
TEST_URN = "urn:li:dataset:(urn:li:dataPlatform:dbt,b2fd91.order_entry_db.order_entry.promotions,PROD)"



# --- Helpers ---
def ensure_dir():
    os.makedirs(EXAMPLES_DIR, exist_ok=True)


@contextlib.contextmanager
def capture_logs(filename):
    """Capture stdout and stderr to a file while still printing to console."""
    class Tee:
        def __init__(self, *files):
            self.files = files
        def write(self, obj):
            for f in self.files:
                f.write(obj)
                f.flush()
        def flush(self):
            for f in self.files:
                f.flush()

    log_file = open(filename, 'w', encoding='utf-8')
    original_stdout = sys.stdout
    original_stderr = sys.stderr
    sys.stdout = Tee(original_stdout, log_file)
    sys.stderr = Tee(original_stderr, log_file)
    try:
        yield
    finally:
        sys.stdout = original_stdout
        sys.stderr = original_stderr
        log_file.close()


def save_example_outputs(result: dict, incident: Incident, log_path: str = None):
    """Save JSON summary, SQL fix, and optionally the log file path."""
    ensure_dir()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name = f"incident_{timestamp}"

    output = {
        "incident_id": incident.id,
        "incident_type": incident.incident_type,
        "trigger_asset_urn": incident.trigger_asset_urn,
        "description": incident.description,
        "classification": result.get("incident", {}).incident_type if result.get("incident") else "unknown",
        "nodes_visited": result.get("nodes_visited", 0),
        "reused_fix": result.get("reused_fix", False),
        "matched_experience_id": result.get("matched_experience_id"),
        "similarity_score": result.get("similarity_score"),
        "evidence": result.get("lineage_evidence", {}),
        "root_cause": result.get("root_cause", ""),
        "fix_proposed": result.get("fix_proposed", ""),
        "outcome": result.get("outcome", "pending"),
        "should_promote": result.get("should_promote", False),
        "promote_reason": result.get("promote_reason", ""),
        "lineage_graph": result.get("lineage_graph", {}),
        "log_file": log_path,
        "timestamp": datetime.now().isoformat()
    }

    # Save JSON
    json_path = os.path.join(EXAMPLES_DIR, f"{base_name}.json")
    with open(json_path, "w") as f:
        json.dump(output, f, indent=2, default=str)
    print(f"Incident data saved to: {json_path}")

    # Save SQL if present
    fix = result.get("fix_proposed", "")
    if fix and any(keyword in fix.upper() for keyword in ("ALTER", "CREATE", "UPDATE", "SELECT", "INSERT", "DROP")):
        sql_path = os.path.join(EXAMPLES_DIR, f"{base_name}.sql")
        with open(sql_path, "w") as f:
            f.write(f"-- Generated by Cortex live run on {datetime.now().isoformat()}\n")
            f.write(f"-- Incident: {incident.description}\n")
            f.write(f"-- Root cause: {result.get('root_cause', '')}\n\n")
            f.write(fix)
        print(f"SQL saved to: {sql_path}")


def approve_in_terminal(incident, fix) -> bool:
    print(f"\n{'='*60}")
    print(f"HUMAN REVIEW — Incident: {incident.description}")
    print(f"Asset: {incident.trigger_asset_urn}")
    print(f"Proposed fix:\n{fix}")
    print(f"{'='*60}")
    answer = input("Approve this fix? [y/n] ").strip().lower()
    return answer == "y"


def main():
    ensure_dir()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_path = os.path.join(EXAMPLES_DIR, f"run_{timestamp}.log")

    print(f"📝 Logging to: {log_path}")

    with capture_logs(log_path):
        incident = Incident(
            trigger_asset_urn=TARGET_URN,
            description="my dashboard just broke and i need a fix",
        )

        result = run_incident(incident, hitl_approve_fn=approve_in_terminal)

        # Save results with reference to log
        save_example_outputs(result, incident, log_path)

        print(f"\n{'='*60}")
        print(f"Final result:")
        print(f"  incident_type: {result.get('incident', {}).incident_type if result.get('incident') else 'unknown'}")
        print(f"  reused_fix:    {result.get('reused_fix', False)}")
        print(f"  nodes_visited: {result.get('nodes_visited')}")
        print(f"  outcome:       {result.get('outcome')}")
        print(f"  promoted:      {result.get('should_promote')}")
        print(f"  log:           {log_path}")
        print(f"{'='*60}\n")


if __name__ == "__main__":
    main()